const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
const CHANGE_MESSAGE_INPUT_VALUE = 'CHANGE_MESSAGE_INPUT_VALUE';
const CHANGE_USERNAME_INPUT_VALUE = 'CHANGE_USERNAME_INPUT_VALUE';
const SET_USERNAME_TO_INITIALSTATE = 'SET_USERNAME_TO_INITIALSTATE';
const USER_IS_WRITTING = 'USER_IS_WRITTING';
const SEND_MESSAGE = 'SEND_MESSAGE';
const HAS_FINISHED_WRITTING = 'HAS_FINISHED_WRITTING';

export {
  WEBSOCKET_CONNECT,
  RECEIVE_MESSAGE,
  CHANGE_MESSAGE_INPUT_VALUE,
  CHANGE_USERNAME_INPUT_VALUE,
  SEND_MESSAGE,
  SET_USERNAME_TO_INITIALSTATE,
  USER_IS_WRITTING,
  HAS_FINISHED_WRITTING
};
