const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
const CHANGE_MESSAGE_INPUT_VALUE = 'CHANGE_MESSAGE_INPUT_VALUE';
const SEND_MESSAGE = 'SEND_MESSAGE';

export {
  WEBSOCKET_CONNECT,
  RECEIVE_MESSAGE,
  CHANGE_MESSAGE_INPUT_VALUE,
  SEND_MESSAGE
};
